name = "MIT18336"
uuid = "58b228b3-1db8-4899-be8a-a12d4debeeaf"
authors = ["bowenszhu <bszhu@fas.harvard.edu>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
BenchmarkTools = "1.3"
FFTW = "1.5"
Plots = "1.33"
julia = "1.8.1"
